version: '3'
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: revivn_hw_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/revivn_hw_development?encoding=utf8&pool=5&timeout=5000&sslmode=disable
    ports:
      - 3000:3000
    depends_on:
      - postgres
  frontend:
    build:
      context: /frontend/schedule-pickup
      dockerfile: Dockerfile
    links:
      - app
    ports:
      - 3050:3000
    depends_on:
      - app
volumes:
  postgres-data:
